nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Location', 'X-Total-Count']
        max_age: 3600
        allow_credentials: true
        forced_allow_origin_value: '*'
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
            forced_allow_origin_value: '*'
